[package]
name = "ndk-build"
version = "0.11.0"
authors = ["The Rust Windowing contributors"]
edition = "2024"
description = "Utilities for building Android binaries"
license = "MIT OR Apache-2.0"
keywords = ["android", "ndk", "apk"]
documentation = "https://docs.rs/ndk-build"
homepage = "https://github.com/rust-mobile/cargo-apk"
repository = "https://github.com/rust-mobile/cargo-apk"
rust-version = "1.88"

[dependencies]
dirs = "6"
dunce = "1"
quick-xml = { version = "0.40", features = ["serialize"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
which = "8"
zip = { version = "8", default-features = false, features = ["deflate"] }
walkdir = "2"
reqwest = { version = "0.13", default-features = true, features = ["deflate", "blocking"] }