[package]
name = "ndk-examples"
version = "0.1.0"
edition = "2024"
publish = false

[target.'cfg(target_os = "android")'.dependencies]
anyhow = "1"
jni = "0.22"
rustix = { version = "1", features = ["pipe"] }
log = "0.4.14"
ndk = { version = "0.10", features = ["api-level-23"], git = "https://github.com/MTaliancich/ndk.git" }
ndk-context = "0.1.1"
android_logger = "0.15"
android-activity = { version = "0.7", features = ["native-activity"], git = "https://github.com/MTaliancich/android-activity.git" }

[[example]]
name = "hello_world"
crate-type = ["cdylib"]

[[example]]
name = "jni_audio"
crate-type = ["cdylib"]

[[example]]
name = "looper"
crate-type = ["cdylib"]
