[package]
name = "cargo-apk"
version = "0.11.0"
authors = ["The Rust Windowing contributors"]
edition = "2024"
description = "Helps cargo build APKs"
license = "MIT OR Apache-2.0"
keywords = ["android", "ndk", "apk"]
documentation = "https://docs.rs/cargo-apk"
homepage = "https://github.com/rust-mobile/cargo-apk"
repository = "https://github.com/rust-mobile/cargo-apk"
rust-version = "1.88"

[dependencies]
anyhow = "1.0.57"
cargo-subcommand = "0.12"
clap = { version = "4", features = ["derive"] }
dunce = "1"
env_logger = "0.11"
ndk-build = { path = "../ndk-build", version = "0.11.0" }
serde = "1"
thiserror = "2"
toml = "1"
